// Sample creative data used by the gallery + detail panel.

const SAMPLE_CREATIVES = [
  {
    id: 'cr_01a', kind: 'image', title: 'Feed · Correndo na cidade',
    placement: 'Instagram Feed · 1:1',
    headline: 'Quem corre muda o ritmo da cidade.',
    body: 'Linha Urban Run X3. Cabedal respirável, entressola com espuma reativa e drop 8mm. Desenvolvido para quem usa o asfalto como pista.',
    hero: 'Sua próxima corrida começa aqui.',
    ctas: ['Comprar agora', 'Saiba mais'],
    format: '1080×1080 png',
    bg: 'linear-gradient(135deg, #fed7aa, #fb923c, #9a3412)',
    status: 'ready',
  },
  {
    id: 'cr_01b', kind: 'image', title: 'Feed · Minimal preto',
    placement: 'Instagram Feed · 1:1',
    headline: 'Menos ruído. Mais passada.',
    body: 'O Urban Run X3 é leve como uma decisão rápida. Se você sabe pra onde vai, isso é tudo que precisa.',
    hero: 'Menos ruído. Mais passada.',
    ctas: ['Comprar agora'],
    format: '1080×1080 png',
    bg: 'linear-gradient(135deg, #1c1917, #44403c, #78716c)',
    status: 'ready',
  },
  {
    id: 'cr_01c', kind: 'image', title: 'Feed · Coral destaque',
    placement: 'Instagram Feed · 1:1',
    headline: 'Ritmo novo. Tênis novo.',
    body: 'Coleção de verão com 15% off na primeira semana. Tamanhos 35 ao 44, todos em estoque.',
    hero: 'Ritmo novo.',
    ctas: ['Aproveitar', 'Ver modelos'],
    format: '1080×1080 png',
    bg: 'linear-gradient(135deg, oklch(0.65 0.18 25), oklch(0.5 0.18 25), oklch(0.35 0.18 25))',
    status: 'ready',
  },
  {
    id: 'cr_01d', kind: 'image', title: 'Feed · Luz natural',
    placement: 'Instagram Feed · 1:1',
    headline: 'Projetado no asfalto, testado no seu dia.',
    body: 'Avaliação média 4.8 de 2.341 corredores. Entrega em 48h para São Paulo e Rio.',
    hero: 'Projetado no asfalto.',
    ctas: ['Conhecer'],
    format: '1080×1080 png',
    bg: 'linear-gradient(135deg, #fef3c7, #fbbf24, #b45309)',
    status: 'streaming',
  },
  {
    id: 'cr_02a', kind: 'video', title: 'Reels · Transformação 15s',
    placement: 'Reels · 9:16 · 15s',
    headline: 'Do sofá à meia maratona.',
    body: 'Seis semanas. Três corridas por semana. Um tênis que acompanha o esforço sem te travar.',
    hero: 'Do sofá à meia maratona',
    ctas: ['Começar agora'],
    format: '1080×1920 mp4',
    duration: '0:15',
    bg: 'linear-gradient(180deg, #1c1917, oklch(0.45 0.15 25))',
    status: 'ready',
  },
  {
    id: 'cr_02b', kind: 'video', title: 'Stories · Product shot',
    placement: 'Stories · 9:16 · 10s',
    headline: 'O novo Urban Run X3.',
    body: 'Três cores, dois solados, infinitas ruas. Confira o lançamento.',
    hero: 'X3',
    ctas: ['Ver lançamento'],
    format: '1080×1920 mp4',
    duration: '0:10',
    bg: 'linear-gradient(180deg, #292524, #57534e)',
    status: 'ready',
  },
  {
    id: 'cr_03a', kind: 'carousel', title: 'Carrossel · 5 motivos',
    placement: 'Feed · 1:1 · 5 cards',
    headline: '5 motivos pra correr com o Urban Run X3.',
    body: 'Do cabedal à entressola, cada detalhe foi pensado pra quem não quer parar.',
    hero: '5 motivos',
    ctas: ['Comprar'],
    format: '5× 1080×1080',
    bg: 'linear-gradient(135deg, #fed7aa, #fb923c)',
    status: 'ready',
  },
  {
    id: 'cr_03b', kind: 'carousel', title: 'Carrossel · Depoimentos',
    placement: 'Feed · 1:1 · 4 cards',
    headline: 'O que os corredores estão dizendo.',
    body: 'Histórias reais de quem trocou o tênis antigo pelo Urban Run.',
    hero: 'Corredores reais',
    ctas: ['Ler histórias'],
    format: '4× 1080×1080',
    bg: 'linear-gradient(135deg, #1c1917, #44403c)',
    status: 'ready',
  },
  {
    id: 'cr_03c', kind: 'carousel', title: 'Carrossel · Técnico',
    placement: 'Feed · 1:1 · 5 cards',
    headline: 'Anatomia do Urban Run X3.',
    body: 'Cada camada, cada costura, cada milímetro explicado.',
    hero: 'Anatomia',
    ctas: ['Ver detalhes'],
    format: '5× 1080×1080',
    bg: 'linear-gradient(135deg, oklch(0.7 0.15 25), oklch(0.5 0.18 25))',
    status: 'streaming',
  },
  {
    id: 'cr_04a', kind: 'copy', title: 'Copy · Variação conversão',
    placement: 'Texto primário + headline',
    headline: 'O tênis que transforma sua passada em confiança.',
    body: 'Leve, respirável, com amortecimento reativo. Urban Run X3 é o upgrade que seu treino estava pedindo. Frete grátis no primeiro pedido.',
    hero: '',
    ctas: ['Comprar agora', 'Saiba mais', 'Ver estoque'],
    format: 'texto',
    bg: 'linear-gradient(135deg, #f5f5f4, #e7e5e4)',
    status: 'ready',
  },
  {
    id: 'cr_04b', kind: 'copy', title: 'Copy · Variação emocional',
    placement: 'Texto primário + headline',
    headline: 'Cada quilômetro é uma versão sua.',
    body: 'Urban Run X3 foi feito pra acompanhar quem entende que correr é mais que exercício — é reencontro. Experimente por 30 dias.',
    hero: '',
    ctas: ['Começar', 'Conhecer linha'],
    format: 'texto',
    bg: 'linear-gradient(135deg, #fafaf9, #e7e5e4)',
    status: 'ready',
  },
  {
    id: 'cr_04c', kind: 'copy', title: 'Copy · Variação promocional',
    placement: 'Texto primário + headline',
    headline: '−15% na estreia. Só até domingo.',
    body: 'Urban Run X3, o tênis de corrida mais pedido do mês, com desconto de lançamento. Use o cupom URBAN15 no checkout.',
    hero: '',
    ctas: ['Aproveitar', 'Ver cupom'],
    format: 'texto',
    bg: 'linear-gradient(135deg, oklch(0.9 0.05 25), oklch(0.75 0.12 25))',
    status: 'ready',
  },
];

function creativesByKind(kind) {
  return SAMPLE_CREATIVES.filter(c => c.kind === kind);
}

Object.assign(window, { SAMPLE_CREATIVES, creativesByKind });
